[phases.setup]
nixPkgs = ["maven", "jdk17", "nodejs", "npm"]

[phases.build]
cmds = [
  "cd frontend-app && npm ci && npm run build",
  "cd backend",
  "mkdir -p src/main/resources/static",
  "cp -r ../frontend-app/build/* src/main/resources/static/",
  "mvn clean package -DskipTests"
]

[phases.install]
cmds = ["echo 'Build complete'"]

[start]
cmd = "java -Dspring.profiles.active=railway -jar backend/target/ecompta-ia-light-2.0.0.jar"
