# render.yaml
services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: Dockerfile.backend
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase: postgres
    
  - type: web
    name: frontend
    env: docker
    dockerfilePath: frontend-app/Dockerfile
    plan: starter
    
databases:
  - name: postgres
    databaseName: ecomptaia
    user: ecomptaia
