# Railway-specific configuration
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${PGUSER:${DATABASE_USERNAME:sa}}
    password: ${PGPASSWORD:${DATABASE_PASSWORD:}}
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true

  sql:
    init:
      mode: never

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.ecomptaia: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
