spring:
  application:
    name: e-compta-ia-light
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}

# Exemple : charger le plan OHADA par défaut
  sql:
    init:
      mode: always
      data-locations: classpath:data-plan-ohada.sql,classpath:data-journaux.sql

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:mon-secret-jwt-tres-long-et-super-securise-pour-jwt-hmac-sha-256-bits-minimum}
  expiration: ${JWT_EXPIRATION:86400000}
