spring:
  application:
    name: e-compta-ia-light
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Exemple : charger le plan OHADA par défaut
  sql:
    init:
      mode: always
      data-locations: classpath:data-plan-ohada.sql

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  port: 8080

jwt:
  secret: mon-secret-jwt-tres-long-et-super-securise-pour-jwt-hmac-sha-256-bits-minimum
  expiration: 86400000
