CREATE TABLE IF NOT EXISTS systemes_comptables (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    libelle VARCHAR(255) NOT NULL,
    description VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS comptes_comptables (
    id UUID PRIMARY KEY,
    numero VARCHAR(20) NOT NULL,
    libelle VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    nature VARCHAR(50) NOT NULL,
    actif BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS journaux (
    id UUID PRIMARY KEY,
    code VARCHAR(10) UNIQUE NOT NULL,
    libelle VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL,
    actif BOOLEAN NOT NULL
);
