name: Full Stack CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn -f backend/pom.xml clean install
      - name: Run Backend Tests
        run: mvn -f backend/pom.xml test

  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: cd frontend-app && npm install
      - name: Build frontend
        run: cd frontend-app && npm run build
      - name: Run frontend tests
        run: cd frontend-app && npm test -- --watchAll=false

  integration:
    name: API Integration Test
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Start Backend
        run: |
          nohup java -jar backend/target/ecompta-ia-light-2.0.0.jar &
          sleep 10
      - name: Run Postman API tests
        run: |
          npm install -g newman
          newman run test-complete-api.postman_collection.json
        continue-on-error: true
