name: Full Stack CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn -f backend/pom.xml clean install
      - name: Run Backend Tests
        run: mvn -f backend/pom.xml test

  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: cd frontend-app && npm install
      - name: Build frontend
        run: cd frontend-app && npm run build
      - name: Run frontend tests
        run: cd frontend-app && npm test -- --watchAll=false

  integration:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Validate Dockerfiles exist
        run: |
          test -f Dockerfile.backend && echo "✓ Dockerfile.backend exists"
          test -f frontend-app/Dockerfile && echo "✓ frontend-app/Dockerfile exists"
      - name: Build Backend Docker Image
        run: docker build -f Dockerfile.backend -t ecompta-backend .
        continue-on-error: true
      - name: Build Frontend Docker Image
        run: docker build -f frontend-app/Dockerfile -t ecompta-frontend ./frontend-app
        continue-on-error: true
